version: '3'
services:
  jenkins:
    image: "jenkins/jenkins:lts-alpine"
    hostname: 'jenkins.example.com'
    networks:
      nova_rede:
        ipv4_address: 200.100.50.50
    volumes:
      - "jenkins_data:/data/db"

volumes:
  jenkins_data: {}

networks:
  nova_rede:
    driver: bridge
    ipam:
      config:
       - subnet: '200.100.50.0/24'
